#!/bin/sh
#
# Starts the sw6106 monitor as a background process.
#

start() {
  printf "Starting sw6106mon: "
  /usr/bin/sw6106mon &
  if [ $? -ne 0 ]; then
    echo "FAIL"
    exit 1
  fi

  echo "OK"
}

stop() {
  printf "Stopping sw6106mon: "
  killall sw6106mon
  echo "OK"
}

restart() {
  stop
  start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
