#!/bin/sh
#
# Starts the sw6106 monitor as a background process.
#

start() {
  printf "Starting sw6106mon: "
  /usr/local/bin/sw6106mon &
	echo "OK" 
}
stop() {
  printf "Stopping sw6106mon: "
	killall sw6106mon
}
restart() {
  stop
  start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
