set(CPACK_PACKAGE_NAME ${PROJECT_NAME}
    CACHE STRING "sw6106mon"
)

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "SW6106 monitor tool"
    CACHE STRING "A simple tool/service to inspect status of SW6106 PSU over i2c bus."
)

set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_PACKAGING_INSTALL_PREFIX "/")
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
SET(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_SOURCE_DIR}/packages")

set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

set(CPACK_DEBIAN_PACKAGE_DEPENDS "libgpiod2")

set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/BortEngineerDude/sw6106mon")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "BortEngineerDude")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE)
set(CPACK_DEB_COMPONENT_INSTALL YES)

include(CPack)
